### ISSUE TITLE
TypeError: init_distributed() got an unexpected keyword argument 'zero_level'

### ISSUE THREAD

**Issue by MohamedAdelNaguib** [HBX-hbx/Mistral-Interact#1]
I am trying to reproduce the same result. I am using a server with 8 GPU, 32 GB each. when I try to run sft.sh script I got this error.

 File "/Mistral-Interact/src/sft.py", line 163, in initialize
    bmt.init_distributed(seed=args.seed, zero_level=3)
TypeError: init_distributed() got an unexpected keyword argument 'zero_level'

these are my environment libraries version:

- GCC version: 11.4.0
- Torch version: 2.2.1
- Linux system version:  22.04
- CUDA version: 12.3
- Torch's CUDA version (as per `torch.cuda.version()`):12.1

**Comment by HBX-hbx** [comment]
What's the version of your installed bmtrain? It seems like the version of bmtrain is too old?

**Comment by HBX-hbx** [comment]
What's the version of your installed bmtrain? In the latest release(Feb 26, 2024) of bmtrain (version 1.0.0) in pip, the init_distributed() function doesn't have an argument called zero_level. You can reinstall it with version 0.2.3.post2. Also, this argument is used for optimization, you can also omit it. I hope it works for you.

**Comment by MohamedAdelNaguib** [comment]
you are right it was a version issue as I installed bmtrain 1.0.0 .Thanks for you help. I have removed the argument. and it passed.
