### ISSUE TITLE
LlamaConfig.__init__() got an unexpected keyword argument 'num_heads_kv'

### ISSUE THREAD

**Issue by MohamedAdelNaguib** [HBX-hbx/Mistral-Interact#2]
Starting the training using sft.sh, I downloaded the base model from hugginface hub and I transformed it into mc weights using the provided scrip `hf_2_mc.py`. 
here is my config file for the model after transforamtion:
`{
    "dim_model": 4096,
    "dim_ff": 14336,
    "num_layers": 32,
    "num_heads": 32,
    "num_heads_kv": 8,
    "dim_head": 128,
    "norm_eps": 1e-05,
    "vocab_size": 32000
}`
and that is my cofig file downloaded from huggingface:
`
{
  "architectures": [
    "MistralForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 14336,
  "max_position_embeddings": 32768,
  "model_type": "mistral",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 8,
  "rms_norm_eps": 1e-05,
  "rope_theta": 10000.0,
  "sliding_window": 4096,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.34.0.dev0",
  "use_cache": true,
  "vocab_size": 32000
}
`

**Comment by HBX-hbx** [comment]
What's the version of model-center? When using pip to install it, the latest version on pip is 1.0.2, where doesn't have a num_heads_kv in LlamaConfig. Maybe you should install from source (version 1.0.3) following the instructions here: https://github.com/OpenBMB/ModelCenter/tree/v1.0.1?tab=readme-ov-file#2-from-source.

**Comment by MohamedAdelNaguib** [comment]
Thanks for you help agin. You are actually right it was a version problem after building modelCenter from  source everything is working now.
