### ISSUE TITLE
Error In Inference

### ISSUE THREAD

**Issue by MohamedAdelNaguib** [HBX-hbx/Mistral-Interact#3]
After training the model, I am currently trying the inference using a server with 8 GPU, 32 GB each. when I try to run test_one_new.sh script I get the error in the screenshot.
![Screenshot 2024-04-12 at 13 54 21](https://github.com/HBX-hbx/Mistral-Interact/assets/47299025/38c69abf-b746-496e-b4c3-8eddefd667f2)

these are my environment library versions:

GCC version: 11.4.0
Torch version: 2.2.1
Linux system version: 22.04
CUDA version: 12.3
Torch's CUDA version (as per torch.cuda.version()):12.1

**Comment by HBX-hbx** [comment]
I think the argument should be 'past_key_values'. What's your version of transformers? Maybe you can upgrade it and try again.

**Comment by yxy-kunling** [comment]
BeamGen.generate(

> 我认为论点应该是“past_key_values”。你的变形金刚版本是什么？也许您可以升级它并重试。

i have the same problem，and transformers.__version__==4.41.2，

**Comment by yxy-kunling** [comment]
> 在训练模型后，我目前正在尝试使用具有 8 个 GPU（每个 32 GB）的服务器进行推理。当我尝试运行test_one_new.sh脚本时，我在屏幕截图中收到错误。 ![屏幕截图 2024-04-12 at 13 54 21](https://private-user-images.githubusercontent.com/47299025/321972970-38c69abf-b746-496e-b4c3-8eddefd667f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTYzMTEsIm5iZiI6MTcxODExNjAxMSwicGF0aCI6Ii80NzI5OTAyNS8zMjE5NzI5NzAtMzhjNjlhYmYtYjc0Ni00OTZlLWI0YzMtOGVkZGVmZDY2N2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE0MjY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNWVkNDZlOTkyZDUyMTU5OGMxMzdlMzVmZjUxZDdlZGZlYTkxMDVjNWVjNmZjY2JlMzg2NzI1MDFlMWZmZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPjKMtyhsAhESwEbZNjt1dBlm8smJPRS-KJDMk5SGyM)
> 
> 以下是我的环境库版本：
> 
> GCC 版本：11.4.0 火炬版本：2.2.1 Linux 系统版本：22.04 CUDA 版本：12.3 Torch 的 CUDA 版本（根据 torch.cuda.version（））：12.1

May I ask how you ultimately resolved it?

**Comment by HBX-hbx** [comment]
> > 在训练模型后，我目前正在尝试使用具有 8 个 GPU（每个 32 GB）的服务器进行推理。当我尝试运行test_one_new.sh脚本时，我在屏幕截图中收到错误。 ![屏幕截图 2024-04-12 at 13 54 21](https://private-user-images.githubusercontent.com/47299025/321972970-38c69abf-b746-496e-b4c3-8eddefd667f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTYzMTEsIm5iZiI6MTcxODExNjAxMSwicGF0aCI6Ii80NzI5OTAyNS8zMjE5NzI5NzAtMzhjNjlhYmYtYjc0Ni00OTZlLWI0YzMtOGVkZGVmZDY2N2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE0MjY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNWVkNDZlOTkyZDUyMTU5OGMxMzdlMzVmZjUxZDdlZGZlYTkxMDVjNWVjNmZjY2JlMzg2NzI1MDFlMWZmZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPjKMtyhsAhESwEbZNjt1dBlm8smJPRS-KJDMk5SGyM)
> > 以下是我的环境库版本：
> > GCC 版本：11.4.0 火炬版本：2.2.1 Linux 系统版本：22.04 CUDA 版本：12.3 Torch 的 CUDA 版本（根据 torch.cuda.version（））：12.1
> 
> May I ask how you ultimately resolved it?

We trained and evaluated Mistral-Interact using transformers==4.34.0.dev0, maybe you can have a try. I think the problem is the version of transformer.

**Comment by yxy-kunling** [comment]
谢了，兄弟，但是我下不了你的版本，4.41.2，4.41.2.dev0和普通的4.34.0都还是报错

**Comment by HBX-hbx** [comment]
> 谢了，兄弟，但是我下不了你的版本，4.41.2，4.41.2.dev0和普通的4.34.0都还是报错

huggingface 上的权重是 hf 格式的，要不就不用 model-center 框架了，直接用 vllm 或者 model.generate 应该问题不大，可以参考 test_one_new.py 里面的 template：

```python
def preprocess_data(task):
    test_prompt = f"<s>User: {SYS_PROMPT}\n\nHere is the task:\n{task}\nAgent: "
    return {"task": task, "prompt": test_prompt}
