### ISSUE TITLE
Dataset using preliminary_test_gpt4.py

### ISSUE THREAD

**Issue by yan-zhaoyu** [HBX-hbx/Mistral-Interact#6]
Dear authors,
I'm using gpt4o run the preliminary_test_gpt4.py script，but can't find this data file _**./vagueness_augmented_test.jsonl'**_ in the repo, how can I get it?

**Comment by HBX-hbx** [comment]
You can refer to the file [here](https://github.com/OpenBMB/Tell_Me_More/blob/master/data/IN3/test.jsonl). Thanks for pointing out!
