### ISSUE TITLE
model_center==1.0.3

### ISSUE THREAD

**Issue by haitao1101** [HBX-hbx/Mistral-Interact#7]
Sorry, I could not find a version that satisfies the requirement model_center==1.0.3. The latest version is 1.0.2. Is there any way to solve it?

**Comment by HBX-hbx** [comment]
The latest version should be installed from GitHub [source](https://github.com/OpenBMB/ModelCenter?tab=readme-ov-file#2-from-source). Hope it will help!

**Comment by haitao1101** [comment]
Alright done, thanks!
