### ISSUE TITLE
Issues encountered during inference

### ISSUE THREAD

**Issue by haitao1101** [HBX-hbx/Mistral-Interact#8]
May I ask about the GPU usage and approximate inference time when using mistral-interact for inference? I noticed that during my reproduction, it takes a long time to perform inference on a single test data point. Is the parameter size of the 7B model very large after fine-tuning?

**Comment by HBX-hbx** [comment]
The inference code provided in [test_one_new.py](https://github.com/OpenBMB/Tell_Me_More/blob/master/src/test_one_new.py) is using the model-center framework. I use one 80G A100 to inference 3s/it. You can try to convert the model weights into huggingface version and inference using vllm, maybe it will be better!
